version: '3'
services:
  pokedexapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGODB: ${MONGODB}
      - PORT: ${PORT}
      - DEFAULT_LIMIT: ${DEFAULT_LIMIT}
  db:
    image: mongo:5.0.0
    container_name: mongo-poke
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGODB_DATABASE:nest-pokemon
    volumes:
      - ./mongo:/data/db